# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  rapidpayapi:
    image: rapidpayapi
    build:
      context: .
      dockerfile: RapidPay.Api/Dockerfile
    ports:
      - 5000:5000
  mssql:
    build: DatabaseConfig/
    #container_name: sql-server
    #image: mcr.microsoft.com/mssql/server:2017-latest
    #image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    restart: always
    #environment:
      #ACCEPT_EULA: "Y"
      #SA_PASSWORD: "admin123"
    ports:
      - 1433:1433
    volumes:
      - my-volume:/var/opt/mssql
      
volumes:
  my-volume:
